# Generated by Django 5.2.9 on 2026-01-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
