# Generated by Django 5.2.9 on 2026-01-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_report_admin_response_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.CharField(max_length=20),
        ),
    ]
