# Generated by Django 5.2.9 on 2026-01-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_batch_end_date_alter_batch_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='server.course'),
        ),
    ]
