# Generated by Django 5.2.9 on 2026-01-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_batch_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
    ]
